# Generated by Django 5.2.8 on 2025-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-demo', unique=True),
            preserve_default=False,
        ),
    ]
